from __future__ import annotations

from pathlib import Path
import tempfile
from typing import Any

CANONICAL_COLUMNS = [
    "timestamp",
    "end_time",
    "relative_time_s",
    "start_relative_time_s",
    "end_relative_time_s",
    "time_is_relative",
    "packet_number",
    "src_ip",
    "dst_ip",
    "src_port",
    "dst_port",
    "protocol",
    "app_protocol",
    "service",
    "bytes",
    "packets",
    "flow_duration",
    "duration_ms",
    "session_state",
    "rule_name",
    "tcp_flags",
    "tcp_flags_seen",
    "ip_version",
    "frame_len",
    "ttl",
    "payload_bytes",
    "icmp_type",
    "icmp_code",
    "dns_query",
    "tls_sni",
    "tls_handshake_type",
    "tls_version",
    "tls_ciphers",
    "tls_extensions",
    "tls_supported_groups",
    "tls_point_formats",
    "tls_server_cipher",
    "tls_server_extensions",
    "ja3_string",
    "ja3_hash",
    "ja3s_string",
    "ja3s_hash",
    "tls_metadata_source",
    "http_host",
    "http_user_agent",
    "dhcp_fingerprint",
    "dhcp_vendor",
    "dhcp_hostname",
    "ssh_hassh",
    "p0f_os",
    "tcp_syn_signature",
    "direction",
    "action",
    "flow_start_reason",
    "flow_end_reason",
    "vlan_id",
    "src_zone",
    "dst_zone",
    "src_asset_group",
    "dst_asset_group",
    "nat_src_ip",
    "nat_dst_ip",
    "dst_asn",
    "dst_country",
    "asset_id",
    "user_id",
    "device_id",
    "sensor_id",
    "pcap_name",
    "mac_src",
    "mac_dst",
    "packet_count",
    "byte_count",
    "bytes_total",
    "src_bytes",
    "dst_bytes",
    "src_packets",
    "dst_packets",
    "src_to_dst_byte_ratio",
    "src_to_dst_packet_ratio",
    "byte_asymmetry",
    "packet_asymmetry",
    "ttl_min",
    "ttl_max",
    "ttl_avg",
    "ttl_range",
    "rtt_ms",
    "jitter_ms",
    "packet_loss_pct",
    "retransmission_count",
    "retransmission_rate",
    "dns_query_length",
    "dns_label_count",
    "dns_query_entropy",
    "dataset_label",
    "traffic_family",
    # Zeek-specific fields for enhanced analysis
    "uid",
    "conn_state",
    "history",
    "local_orig",
    "local_resp",
    "missed_bytes",
    "orig_ip_bytes",
    "resp_ip_bytes",
    "orig_pkts",
    "resp_pkts",
    "ip_proto",
]
NUMERIC_COLUMNS = {
    "packet_number",
    "relative_time_s",
    "start_relative_time_s",
    "end_relative_time_s",
    "src_port",
    "dst_port",
    "bytes",
    "packets",
    "flow_duration",
    "duration_ms",
    "frame_len",
    "ttl",
    "payload_bytes",
    "icmp_type",
    "icmp_code",
    "vlan_id",
    "dst_asn",
    "packet_count",
    "byte_count",
    "bytes_total",
    "src_bytes",
    "dst_bytes",
    "src_packets",
    "dst_packets",
    "src_to_dst_byte_ratio",
    "src_to_dst_packet_ratio",
    "byte_asymmetry",
    "packet_asymmetry",
    "ttl_min",
    "ttl_max",
    "ttl_avg",
    "ttl_range",
    "rtt_ms",
    "jitter_ms",
    "packet_loss_pct",
    "retransmission_count",
    "retransmission_rate",
    "dns_query_length",
    "dns_label_count",
    "dns_query_entropy",
    "missed_bytes",
    "orig_ip_bytes",
    "resp_ip_bytes",
    "orig_pkts",
    "resp_pkts",
    "ip_proto",
}
CACHE_DIR = Path(tempfile.gettempdir()) / ".network-traffic-analysis-cache"
SUPPORTED_PATTERNS = ("*.csv", "*.parquet", "*.json", "*.jsonl", "*.xlsx", "*.xls")
FLOW_PREFERRED_FIELDS = {
    "flow_duration",
    "duration_ms",
    "app_protocol",
    "service",
    "direction",
    "action",
    "session_state",
    "traffic_family",
}
PACKET_PREFERRED_FIELDS = {
    "packet_number",
    "frame_len",
    "ttl",
    "payload_bytes",
    "tcp_flags",
    "icmp_type",
    "icmp_code",
    "mac_src",
    "mac_dst",
    "pcap_name",
}
SUPPORTED_ANOMALY_RULES = [
    "scan-source",
    "volume-spike",
    "rare-port",
    "failure-rate",
    "syn-scan",
    "rst-heavy",
    "handshake-failure",
    "icmp-probe",
    "small-packet-burst",
]
CAPABILITY_GUIDANCE = {
    "overview-report": "Use for dataset-wide communication profile and high-level protocol mix.",
    "scan-review": "Use for broad-destination or broad-port behavior and likely scan sources.",
    "session-review": "Use for session quality, short-lived flows, resets, and connection-state triage.",
    "short-connection-review": "Use for formal short-connection analysis with both wide and narrow flow-level heuristics.",
    "protocol-review": "Use for DNS/TLS/HTTP/SMTP and other protocol-specific traffic characteristics.",
    "dns-tunnel-review": "Use for DNS tunneling hypotheses, long high-entropy queries, abnormal DNS timing patterns, and NXDOMAIN-heavy DNS activity.",
    "data-exfiltration-review": "Use for potential data exfiltration patterns such as outbound byte asymmetry, large transfers, long-lived flows, and multi-destination spread.",
    "lateral-movement-review": "Use for internal east-west spread, credential-service fan-out, risky internal session states, and likely lateral movement candidates.",
    "zeek-review": "Use for Zeek semantic evidence from conn/dns/http/ssl/weird logs generated during preprocessing.",
    "packet-review": "Use for packet-level flags, ICMP behavior, handshake quality, and burst evidence.",
    "signature-review": "Use for Aho-Corasick-style indicator matching across dns_query, tls_sni, http_host, service, and rule_name fields.",
    "periodicity-review": "Use for C2-like or structured periodic traffic patterns with autocorrelation and RCF scoring.",
    "risk-fusion-review": "Use for a final ranked risk view that fuses flow anomalies, Zeek semantic evidence, and signature hits by source IP.",
    "query": "Use for explicit thresholds, custom filters, and analyst-defined SQL investigations.",
    "detect-anomaly": "Use only with supported built-in anomaly rules. Query list-capabilities first if unsure.",
    "encrypted-flow-analysis": "Use for JA3/JA3S TLS fingerprinting, encrypted application classification, and encrypted tunnel detection.",
    "device-identification": "Use for device type identification (IoT, mobile, server, desktop) based on TLS/HTTP/DHCP fingerprints.",
    "behavior-analysis": "Use for host/user behavior baseline building, behavioral shift detection, and anomaly profiling.",
    "graph-analysis": "Use for network communication graph construction, community detection, centrality analysis, and attack path discovery.",
    "qos-analysis": "Use for service-quality triage with throughput, loss, retransmission, asymmetry, and timing-instability evidence when available.",
    "root-cause-analysis": "Use for heuristic attribution that ranks which fields contributed most to anomaly scores.",
    "threat-intel-match": "Use for matching network indicators (IPs, domains) against explicitly loaded IOC feeds plus clearly labeled local heuristics.",
    "forecast-traffic": "Use for traffic volume forecasting, trend analysis, capacity risk estimation, and future anomaly prediction.",
    "detect-concept-drift": "Use for detecting concept drift in data streams with ADWIN-like mean-shift screening.",
}
